### ISSUE TITLE
Can certain types of dependencies e.g. peer dependencies be excluded?

### ISSUE THREAD

**Issue by mohanraj-r** [idan-at/eslint-plugin-package-json-dependencies#11]
Thanks for the useful plugin!
I would like to use controlled-versions rule to pin versions to fixed. But I would like to exclude the peer deps as they are usually `^`ed. Is this possible ?

Also noticed that applying `eslint --fix` with the plugin with controlled-versions rule resulted changing the following peer deps with range versions to `undefined`
```
"pino-pretty": "^6.0.0 || ^10.0.0"
"@angular/common": "14 - 16",
```

to 
```
"pino-pretty": "undefined"
"@angular/common": "undefined",
````

**Comment by idan-at** [comment]
Hi Mohan!

Indeed those `undefined` fixes are not expected. I've opened a PR to fix that.
Regarding defining the granularity for different dependencies types - that is not possible ATM, but I can probably get it done soon

**Comment by mohanraj-r** [comment]
Thank you Idan!
