### ISSUE TITLE
config for controlled-versions rule

### ISSUE THREAD

**Issue by mohanraj-r** [idan-at/eslint-plugin-package-json-dependencies#15]
Thanks for implementing and releasing the features quickly!

When testing it out I am not able to figure out how to configure the rule correctly - tried 
```
'package-json-dependencies/controlled-versions': [
          'warn',
          {granularity: {dependencies: 'fixed', devDependencies: 'fixed'}},
        ],
```

But it leads to error
```
Oops! Something went wrong! :(

ESLint: 8.52.0

Error: .eslintrc.js#overrides[3]:
	Configuration for rule "package-json-dependencies/controlled-versions" is invalid:
	Value {"dependencies":"fixed","devDependencies":"fixed"} should be string.

```

**Comment by mohanraj-r** [comment]
Also would not specifying granularity for a type of dependency e.g. peer result it not being processed by the rule or would it process it defaulting to `fixed`? In that case is there an option to ignore a type of dependency?

**Comment by idan-at** [comment]
Hey,

I've only published a new version now. Make sure you're using 1.0.18

**Comment by idan-at** [comment]
> Also would not specifying granularity for a type of dependency e.g. peer result it not being processed by the rule or would it process it defaulting to fixed? In that case is there an option to ignore a type of dependency?

In case you don't provide granularity for a specific dependencies type (e.g peer), then it will default to "fixed"

**Comment by mohanraj-r** [comment]
Thanks Idan. I saw the merged PRs and assumed would be published - should have checked npm timestamp 🤦 
Tested out with 1.0.18 - it doesn't error anymore but eslint fix doesn't fix the package json as before. Is the following config correct

```
'package-json-dependencies/controlled-versions': [
          'warn',
          {granularity: {dependencies: 'fixed', devDependencies: 'fixed'}},
        ],
```

Would it be possible to add an option to skip a type of dependency e.g. peer?

**Comment by mohanraj-r** [comment]
nm, I fixed the config and now it is working. But inability to exclude specific types of dependencies is an issue. I did try setting `peerDependencies: 'minor',` because it should satisfy most cases but then it does fix the following 

```
"peerDependencies": {
    "react": ">=18.0.0",
    "react-dom": ">=18.0.0"
  }
```
to
```
"peerDependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }
```

It would be great if there is a way to skip/ignore a type of dependency.

**Comment by idan-at** [comment]
Hey,

you can set the exclude patterns to make the rule skip specific dependencies, by name.

in your case, setting it to [“react*”] will make the rule skip react and react-dom

**Comment by idan-at** [comment]
@mohanraj-r Closing this one, please open another issue if you have any more questions
