### ISSUE TITLE
Can we make controlled-versions work with "*"?

### ISSUE THREAD

**Issue by fasiha** [idan-at/eslint-plugin-package-json-dependencies#16]
I have a few dependencies that use `*`, for example `"react": "*"` or `"@mycompany/mypackage": "workspace:*"`, and if I use the awesome `controlled-version` rule, it doesn't work for these because (1) they're not `semver` nor (2) git nor (3) file dependencies.

Would you be open to a PR adding a third function to this https://github.com/idan-at/eslint-plugin-package-json-dependencies/blob/e0dd358b5cfe9cddf77d521c618d3f31ea95967b/src/rules/controlled-versions.ts#L22-L23 something like,
```ts
const isWildcardDependency = (version: string): boolean => version.endsWith("*");
```
to automatically skip these?

I know I could use `excludePatterns` but there's enough mix-and-match in my monorepo that the dependencies have pinned versions in one workspace but wildcard versions in others 😓

Let me know if you're interested in this and I can make that PR!

**Comment by fasiha** [comment]
Or maybe other users of this rule do NOT want `*` to be treated like file/git dependencies and ignored 😮? If so, perhaps we'd need another argument, something like `permitWildcards`?

**Comment by idan-at** [comment]
Hey Ahmed, 

controlled-versions is specifically designed to replace wildcards with specific versions. If you still want to use a wildcard, the excludePatterns is exactly for that use case :)

I’m not sure how the rule handles workspace dependencies (workspace:xx), but for that specific case we can probably add a new flag, something like ignoreWorkspacePackages. Will that help?

**Comment by fasiha** [comment]
Thanks for the insightful feedback @idan-at!!! Your explanation makes total sense, I will add `excludePatterns` for the dependencies we have pure wildcards for (`"react": "*"`).

A new flag `ignoreWorkspacePackages` would definitely help me but I'm honestly not sure how others structure their monorepos—I'm not sure if the best thing to offer monorepo users would be "ignore all workspace packages", because maybe the bulk of your monorepo users want to do something else. I personally can easily construct an `excludePatterns` string for the workspace dependencies so I have a workaround 😄

**Comment by idan-at** [comment]
I agree, the new flag might be too broad.

I’m glad you have a workaround, closing this issue :)
