### ISSUE TITLE
Forbid spaces in versions

### ISSUE THREAD

**Issue by fasiha** [idan-at/eslint-plugin-package-json-dependencies#17]
Hello again! We spoke last time in https://github.com/idan-at/eslint-plugin-package-json-dependencies/issues/16 and I wanted to pitch a potentially related rule that might be broadly useful.

Background: we accidentally added a version to our package.json, `workspace: *`. Note the space there, which is invalid and causes `pnpm` et al. to do a full resolution scan each time.

Suggestion: add a rule that forbids *spaces* in versions, whether they're excluded or git dependencies or file dependencies.

Do you think such a rule would be broadly useful? Does it have a place in this plugin? Thanks for considering!

**Comment by idan-at** [comment]
Hey,

I'm fine with adding another rule, but I wouldn't want it to be that specific. I tried giving it some thought, would you find a `valid-versions` rule useful? the rule will check whether your dependency format is valid

**Comment by fasiha** [comment]
`valid-versions` would be great! Is there a library that, say, npm/pnpm/yarn use to validate versions and that includes all the various official versions in https://docs.npmjs.com/cli/v6/configuring-npm/package-json#dependencies as well as `workspace:` prefixes and anything else weird that `package.json`s have come to have?

**Comment by idan-at** [comment]
I've added it under #18, and the rule is now available in version 1.0.19 :)
