### ISSUE TITLE
Ignore packages that are not semver for controlled versions

### ISSUE THREAD

**Issue by Tallyb** [idan-at/eslint-plugin-package-json-dependencies#4]
Toda for a great plugin. 
I think packages that do not have a semver (e.g. point to a git) should be automatically ignored when checking controlled versions.

**Comment by idan-at** [comment]
I agree. Both `git` and `file` links should be excluded. I'm on it.

**Comment by idan-at** [comment]
Release `1.0.14` includes this change :)
